//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por el Generador Inteligente C#
//     Nota: El formulario Form1 es un archivo único completo.
//     Todo el código está en Form1.cs, incluyendo la creación de controles.
// </auto-generated>
//------------------------------------------------------------------------------
// Este Designer está vacío porque el formulario es un archivo único.
// Los controles se crean dinámicamente en el código de Form1.cs

/// <summary>
/// Método requerido para el soporte del diseñador.
/// Este método está vacío porque los controles se crean en el código.
/// </summary>